### ISSUE TITLE
Waf build fails fedora 20

### ISSUE THREAD

**Issue by Dragonius** [xmms2/promoe#1]
First is ./waf configure

./waf configure
Check for program g++ or c++             : /usr/bin/g++
Check for program cpp                    : /usr/bin/cpp
Check for program ar                     : /usr/bin/ar
Check for program ranlib                 : /usr/bin/ranlib
Check for program qmake-qt4              : /usr/bin/qmake-qt4
Check for program qmake4                 : not found
Check for program qmake                  : /usr/lib/qt-3.3/bin/qmake
Check for program uic-qt3                : not found
Check for program uic3                   : /usr/bin/uic3
Check for program uic-qt4                : /usr/bin/uic-qt4
Checking for uic version                 : ok (version 4.8.6)
Check for program moc-qt4                : /usr/bin/moc-qt4
Check for program rcc                    : /usr/bin/rcc
Check for program lrelease-qt4           : /usr/bin/lrelease-qt4
Check for program lupdate-qt4            : /usr/bin/lupdate-qt4
Check for program pkg-config             : /usr/bin/pkg-config
Checking for QtCore_debug                : not found
Checking for QtGui_debug                 : not found
Checking for QtUiTools_debug             : not found
Checking for QtNetwork_debug             : not found
Checking for QtOpenGL_debug              : not found
Checking for QtSql_debug                 : not found
Checking for QtSvg_debug                 : not found
Checking for QtTest_debug                : not found
Checking for QtXml_debug                 : not found
Checking for QtWebKit_debug              : not found
Checking for Qt3Support_debug            : not found
Checking for QtCore                      : ok
Checking for QtGui                       : ok
Checking for QtUiTools                   : ok
Checking for QtNetwork                   : ok
Checking for QtOpenGL                    : ok
Checking for QtSql                       : ok
Checking for QtSvg                       : ok
Checking for QtTest                      : ok
Checking for QtXml                       : ok
Checking for QtWebKit                    : ok
Checking for Qt3Support                  : ok
Checking for xmms2-client-cpp            : ok
Checking for libarchive                  : ok
Checking for avahi-client                : ok
Checking for avahi-qt4                   : ok

then i do ./waf build 

and error come on 

[ 63/105] qxx: dir_iterator/archive_read_open_qiodevice.cpp -> _build_/default/dir_iterator/archive_read_open_qiodevice_1.o
../dir_iterator/archive_read_open_qiodevice.cpp: Funktio ”int archive_read_open_qiodevice(archive*, QIODevice*)”:
../dir_iterator/archive_read_open_qiodevice.cpp:88:51: virhe: virheellinen muunnos tyypistä ”archive_skip_t (*)(archive*, void*, archive_skip_t) {aka int (*)(archive*, void*, int)}” tyypiksi ”int64_t (*)(archive*, void*, int64_t) {aka long long int (*)(archive*, void*, long long int)}” [-fpermissive]
          qiodevice_read_skip, qiodevice_read_close));
                                                   ^
In file included from ../dir_iterator/archive_read_open_qiodevice.cpp:31:0:
/usr/include/archive.h:421:15: virhe:   alustettaessa funktion ”int archive_read_open2(archive*, void*, int (*)(archive*, void*), ssize_t (*)(archive*, void*, const void**), int64_t (*)(archive*, void*, int64_t), int (*)(archive*, void*))” argumenttia 5 [-fpermissive]
 __LA_DECL int archive_read_open2(struct archive *, void *_client_data,
               ^
Waf: Leaving directory `/root/yum/promoe/_build_'
Build failed:  -> task failed (err #1):
        {task: qxx_task archive_read_open_qiodevice.cpp -> archive_read_open_qiodevice_1.o}

**Comment by Dragonius** [comment]
[ 82/105] qxx: dir_iterator/archive_read_open_qiodevice.cpp -> _build_/default/dir_iterator/archive_read_open_qiodevice_1.o
17:24:29 runner system command -> ['/usr/bin/g++', '-Idefault/dir_iterator', '-I../dir_iterator', '-I/root/yum/promoe/_build_/default', '-I/usr/include/QtCore', '-I/usr/include/QtGui', '-DQT_SHARED', '-DQT_SHARED', '-DQT_SHARED', '../dir_iterator/archive_read_open_qiodevice.cpp', '-c', '-o', 'default/dir_iterator/archive_read_open_qiodevice_1.o']
../dir_iterator/archive_read_open_qiodevice.cpp: Funktio ”int archive_read_open_qiodevice(archive*, QIODevice*)”:
../dir_iterator/archive_read_open_qiodevice.cpp:88:51: virhe: virheellinen muunnos tyypistä ”archive_skip_t (*)(archive*, void*, archive_skip_t) {aka int (*)(archive*, void*, int)}” tyypiksi ”int64_t (*)(archive*, void*, int64_t) {aka long long int (*)(archive*, void*, long long int)}” [-fpermissive]
          qiodevice_read_skip, qiodevice_read_close));
                                                   ^
In file included from ../dir_iterator/archive_read_open_qiodevice.cpp:31:0:
/usr/include/archive.h:421:15: virhe:   alustettaessa funktion ”int archive_read_open2(archive*, void*, int (*)(archive*, void*), ssize_t (*)(archive*, void*, const void**), int64_t (*)(archive*, void*, int64_t), int (*)(archive*, void*))” argumenttia 5 [-fpermissive]
 __LA_DECL int archive_read_open2(struct archive *, void *_client_data,
               ^
Waf: Leaving directory `/root/yum/promoe/_build_'
Build failed:  -> task failed (err #1):
        {task: qxx_task archive_read_open_qiodevice.cpp -> archive_read_open_qiodevice_1.o}
  File "./waf", line 154, in <module>
        Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/root/yum/promoe/.waf-1.5.14-c027e86ae7f2c5cf77a02bd78b9b1c85/wafadmin/Scripting.py", line 107, in prepare
        error(str(e))

**Comment by Dragonius** [comment]
[ 82/105] qxx: dir_iterator/archive_read_open_qiodevice.cpp -> _build_/default/dir_iterator/archive_read_open_qiodevice_1.o
17:32:10 runner system command -> ['/usr/bin/g++', '-Idefault/dir_iterator', '-I../dir_iterator', '-I/root/yum/promoe/_build_/default', '-I/usr/include/QtCore', '-I/usr/include/QtGui', '-DQT_SHARED', '-DQT_SHARED', '-DQT_SHARED', '../dir_iterator/archive_read_open_qiodevice.cpp', '-c', '-o', 'default/dir_iterator/archive_read_open_qiodevice_1.o']
../dir_iterator/archive_read_open_qiodevice.cpp: Funktio ”int archive_read_open_qiodevice(archive*, QIODevice*)”:
../dir_iterator/archive_read_open_qiodevice.cpp:88:51: virhe: virheellinen muunnos tyypistä ”archive_skip_t (*)(archive*, void*, archive_skip_t) {aka int (*)(archive*, void*, int)}” tyypiksi ”int64_t (*)(archive*, void*, int64_t) {aka long long int (*)(archive*, void*, long long int)}” [-fpermissive]
          qiodevice_read_skip, qiodevice_read_close));
                                                   ^
In file included from ../dir_iterator/archive_read_open_qiodevice.cpp:31:0:
/usr/include/archive.h:421:15: virhe:   alustettaessa funktion ”int archive_read_open2(archive*, void*, int (*)(archive*, void*), ssize_t (*)(archive*, void*, const void**), int64_t (*)(archive*, void*, int64_t), int (*)(archive*, void*))” argumenttia 5 [-fpermissive]
 __LA_DECL int archive_read_open2(struct archive *, void *_client_data,
               ^
17:32:30 envhash 'UHN%y\x933\xfa(]\xcf\x807\x11|\x11' ['/usr/bin/ar', 'rcs', '[]', '[]']
17:32:30 task task
        {task: static_link playlistmodel_1.o,xclient_1.o,xconfig_1.o,xplayback_1.o,xclientcache_1.o,xcollection_1.o,xmmsqt4_1.o,volumehandler_1.o -> libbackend_lib.a} must run as it was never run before or the task code changed
Waf: Leaving directory `/root/yum/promoe/_build_'
Build failed:  -> task failed (err #1):
        {task: qxx_task archive_read_open_qiodevice.cpp -> archive_read_open_qiodevice_1.o}
  File "./waf", line 154, in <module>
        Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/root/yum/promoe/.waf-1.5.14-c027e86ae7f2c5cf77a02bd78b9b1c85/wafadmin/Scripting.py", line 107, in prepare
        error(str(e))

**Comment by Dragonius** [comment]
Here with 4x verbose

**Comment by dsvensson** [comment]
Please try https://github.com/dsvensson/promoe

**Comment by Dragonius** [comment]
Found working rpm file fron Suse repo.
http://rpm.pbone.net/index.php3?stat=3&search=promoe&srodzaj=3 .

I try build svenson version when i get home

**Comment by dsvensson** [comment]
@Dragonius: Did it work? If not, what issues?

**Comment by dsvensson** [comment]
@Dragonius Any luck building with that branch?

**Comment by Dragonius** [comment]
Building Now 9:43 30.9.2015 
Failed at 09:47:51 30.9.2015
it failed same problem. archive_read_open_qiodevice.cpp

[55/87] qxx: dir_iterator/archive_read_open_qiodevice.cpp -> build/dir_iterator/archive_read_open_qiodevice.cpp.1.o
../dir_iterator/archive_read_open_qiodevice.cpp: Funktio ”int archive_read_open_qiodevice(archive*, QIODevice*)”:
../dir_iterator/archive_read_open_qiodevice.cpp:88:51: virhe: virheellinen muunnos tyypistä ”archive_skip_t (*)(archive*, void*, archive_skip_t) {aka int (*)(archive*, void*, int)}” tyypiksi ”int64_t (*)(archive*, void*, int64_t) {aka long long int (*)(archive*, void*, long long int)}” [-fpermissive]
          qiodevice_read_skip, qiodevice_read_close));
                                                   ^
In file included from ../dir_iterator/archive_read_open_qiodevice.cpp:31:0:
/usr/include/archive.h:421:15: virhe:   alustettaessa funktion ”int archive_read_open2(archive*, void*, int (*)(archive*, void*), ssize_t (*)(archive*, void*, const void**), int64_t (*)(archive*, void*, int64_t), int (*)(archive*, void*))” argumenttia 5 [-fpermissive]
 __LA_DECL int archive_read_open2(struct archive *, void *_client_data,
               ^
Waf: Leaving directory `/root/yum/promoe/build'
Build failed
 -> task in 'dir_iterator' failed (exit status 1):
        {task 156312332: qxx archive_read_open_qiodevice.cpp -> archive_read_open_qiodevice.cpp.1.o}
['/usr/bin/g++', '-I/root/yum/promoe/build', '-I/root/yum/promoe', '-I/root/yum/promoe/build/dir_iterator', '-I/root/yum/promoe/dir_iterator', '-I/usr/include/QtCore', '-I/usr/include/QtGui', '-DQT_SHARED', '-DQT_SHARED', '../dir_iterator/archive_read_open_qiodevice.cpp', '-c', '-o', 'dir_iterator/archive_read_open_qiodevice.cpp.1.o']

**Comment by Dragonius** [comment]
uname -a
Linux Serveri1 3.19.8-100.fc20.i686+PAE #1 SMP Tue May 12 17:27:49 UTC 2015 i686 i686 i386 GNU/Linux

**Comment by dsvensson** [comment]
Did you perform a git clean -xdf after you checked out the branch, and before you built? The branch mentioned works fine in F22 at least. It would also be helpful if you set your LC_ALL=C environment so your g++ messages aren't localized.

**Comment by Dragonius** [comment]
Run export LC_ALL=C
15:13:49-root@Serveri1:~/yum/promoe$ locale
LANG=fi_FI.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

15:14:45-root@Serveri1:~/yum/promoe$ date
Fri Oct 30 15:16:30 EET 2015

stil same problem. cleaned directory and cloned.
./waf configure
./waf build.

[ 40/101]  qxx: dir_iterator/diriteratorbase.cpp -> build/dir_iterator/diriteratorbase.cpp.1.o
../dir_iterator/archive_read_open_qiodevice.cpp: In function 'int archive_read_open_qiodevice(archive*, QIODevice*)':
../dir_iterator/archive_read_open_qiodevice.cpp:88:51: error: invalid conversion from 'archive_skip_t (*)(archive*, void*, archive_skip_t) {aka int (*)(archive*, void*, int)}' to 'int64_t (*)(archive*, void*, int64_t) {aka long long int (*)(archive*, void*, long long int)}' [-fpermissive]
          qiodevice_read_skip, qiodevice_read_close));
                                                   ^
In file included from ../dir_iterator/archive_read_open_qiodevice.cpp:31:0:
/usr/include/archive.h:421:15: error:   initializing argument 5 of 'int archive_read_open2(archive*, void*, int (*)(archive*, void*), ssize_t (*)(archive*, void*, const void**), int64_t (*)(archive*, void*, int64_t), int (*)(archive*, void*))' [-fpermissive]
 __LA_DECL int archive_read_open2(struct archive *, void *_client_data,
               ^
Waf: Leaving directory `/root/yum/promoe/build'
Build failed
 -> task in 'dir_iterator' failed (exit status 1):
        {task 165880812: qxx archive_read_open_qiodevice.cpp -> archive_read_open_qiodevice.cpp.1.o}
['/usr/bin/g++', '-I/root/yum/promoe/build', '-I/root/yum/promoe', '-I/root/yum/promoe/build/dir_iterator', '-I/root/yum/promoe/dir_iterator', '-I/usr/include/QtCore', '-I/usr/include/QtGui', '-DQT_SHARED', '-DQT_SHARED', '../dir_iterator/archive_read_open_qiodevice.cpp', '-c', '-o', 'dir_iterator/archive_read_open_qiodevice.cpp.1.o']


is problem "error: invalid conversion from 'archive_skip_t "

**Comment by dsvensson** [comment]
Patches accepted, or just upgrade to latest Fedora and be done with it, or perhaps wait until F23.

**Comment by Dragonius** [comment]
Fork dsvensson/promoe Works for me, Using Fedora 30. 

im using QT 5 to make program to build. Thanks you help.
