### ISSUE TITLE
Will promoe be ported onto Qt5?

### ISSUE THREAD

**Issue by hosiet** [xmms2/promoe#3]
It seems that promoe is still using Qt4, which is dead upstream for quite a few years. Will promoe be ported onto Qt5 in the future?

Thanks!

**Comment by dsvensson** [comment]
Sure, it's probably trivial. Try it yourself and I can help out if you get stuck.

**Comment by Dragonius** [comment]
dsvensson/promoe Has some QT 5 support. i got it running by it.

**Comment by Malvineous** [comment]
Closing because that QT5 code has been merged in here for some time now.

**Comment by hosiet** [comment]
@Malvineous Can you indicate where was Qt5 code merged? Looking at https://github.com/xmms2/promoe/commits/master , I do not see anything Qt5-related.

**Comment by Malvineous** [comment]
I presume it's da55656 and related commits.
